# Generated by Django 5.0.6 on 2024-11-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(default=1),
        ),
    ]
