# Generated by Django 5.0.6 on 2024-11-19 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0007_task_end_time_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('priority_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='TaskApp.task')),
            ],
            options={
                'ordering': ['-priority_score'],
            },
        ),
    ]
